apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: client

resources:
- namespace.yml
- deployment.yml

secretGenerator:
- name: ai
  type: Opaque
  envs:
  - .env.secrets

configMapGenerator:
- name: request
  behavior: create
  envs:
  - .env.configs